---
- name: yum install
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ vim.yum_packages }}"  
  tags: vim

- name: git clone
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ vim.git }}"
  tags: vim

- name: check vim
  stat: path=/usr/local/share/vim
  register: vim_bin
  become: yes
  tags: vim

- block:
  - name: distclean vim
    command:  chdir=/home/vagrant/git/github/vim/ make distclean

  - name: configure vim
    command:  chdir=/home/vagrant/git/github/vim/ ./configure --enable-gui=yes --with-features=huge --enable-multibyte --enable-luainterp=dynamic --enable-gpm --enable-cscope --enable-fontset --enable-fail-if-missing --prefix=/usr/local --enable-python3interp=dynamic

  - name: build vim
    make:
      chdir:  /home/vagrant/git/github/vim/

  - name: install vim
    make:
      chdir:  /home/vagrant/git/github/vim/
      target: install

  when: not vim_bin.stat.exists
  become: yes
  tags: vim

- name: generate .vimrc with plugins
  template: src=.vimrc.j2 dest=~/.vimrc
  tags: vimrc
  
- name: copy hybrid colorscheme
  copy:
    src: /home/vagrant/git/github/vim-hybrid/colors/hybrid.vim
    dest: /usr/local/share/vim/vim80/colors
    owner:  root
    group:  root
    mode: 0644
    force:  yes
  become: yes
  tags: vimrc

- name: vim template directory
  file: path='~/.vim/template/' state=directory
  tags: vimrc

- name: template php
  template: src=template.php.j2 dest=~/.vim/template/template.php
  tags: vimrc

- name: template python
  template: src=template.py.j2 dest=~/.vim/template/template.py
  tags: vimrc
